#!/usr/bin/env bash
# deploy_aws.sh — one-command PriceWatch deployment to AWS Tokyo box (or any Ubuntu host)
#
# ⚠️  NOT TESTED IN SANDBOX — docker is blocked in the agent sandbox.
#     Run this yourself; expect 1–2 rounds of debugging (network timing, port firewall, etc.)
#
# Usage (from your local WSL terminal):
#
#     export POSTGRES_PASSWORD='your-strong-password'
#     export TELEGRAM_BOT_TOKEN='123456:ABC...'   # optional; leave unset to skip alerts
#     export TELEGRAM_CHAT_ID='your_chat_id'      # optional
#     # SSH_KEY defaults to sol-grid-trader.pem in this dir
#     bash deploy_aws.sh
#
# Re-run at any time to update code (idempotent).
# Secrets flow: local env → remote .env (0600) → container; never printed, never committed.
#
# Requires on remote box: Docker CE + docker-compose-plugin (V2 CLI).
# See docs/DEPLOY.md for full pre-requisites.
#
# shellcheck disable=SC2029,SC2087

set -euo pipefail
cd "$(dirname "$0")"

# ── Config ────────────────────────────────────────────────────────────────────
AWS_HOST="ubuntu@57.182.243.118"
SSH_KEY="${SSH_KEY:-sol-grid-trader.pem}"
REMOTE_DIR="/home/ubuntu/pricewatch"
APP_PORT="${APP_PORT:-8000}"
SSH_OPTS=(-i "$SSH_KEY" -o StrictHostKeyChecking=no -o ConnectTimeout=10)

# ── Pre-flight checks (local) ─────────────────────────────────────────────────
echo "=== PriceWatch AWS deploy — $(date -u) ==="

if [ ! -f "$SSH_KEY" ]; then
    echo "ERROR: SSH key '$SSH_KEY' not found." >&2
    echo "  Put sol-grid-trader.pem here, or: export SSH_KEY=/path/to/key" >&2
    exit 1
fi

if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    echo "ERROR: POSTGRES_PASSWORD is not set." >&2
    echo "  export POSTGRES_PASSWORD='your-strong-password'" >&2
    exit 1
fi

# JWT_SECRET: generate if not provided
if [ -z "${JWT_SECRET:-}" ]; then
    echo "[info] JWT_SECRET not set — generating with openssl..."
    JWT_SECRET="$(openssl rand -hex 32)"
fi

echo "[1/7] Checking SSH connectivity..."
ssh "${SSH_OPTS[@]}" "$AWS_HOST" "echo '  box is reachable'" || {
    echo "ERROR: Cannot reach $AWS_HOST. Check firewall / key." >&2
    exit 1
}

echo "[2/7] Packing project (excluding secrets, caches, test fixtures)..."
TARBALL="$(mktemp "${TMPDIR:-/tmp}/pricewatch.XXXXXX.tgz")"
tar \
    --exclude='./.git' \
    --exclude='./.env' \
    --exclude='./__pycache__' \
    --exclude='./app/__pycache__' \
    --exclude='./alembic/__pycache__' \
    --exclude='./alembic/versions/__pycache__' \
    --exclude='./.ruff_cache' \
    --exclude='./.pytest_cache' \
    --exclude='./tests' \
    --exclude='./frontend/node_modules' \
    --exclude='./frontend/dist' \
    -czf "$TARBALL" -C . .

echo "[3/7] Shipping code to box:$REMOTE_DIR ..."
ssh "${SSH_OPTS[@]}" "$AWS_HOST" "mkdir -p '$REMOTE_DIR'"
scp "${SSH_OPTS[@]}" "$TARBALL" "$AWS_HOST:$REMOTE_DIR/_deploy.tgz"
ssh "${SSH_OPTS[@]}" "$AWS_HOST" "
    cd '$REMOTE_DIR'
    tar -xzf _deploy.tgz
    rm -f _deploy.tgz
    echo '  code unpacked.'
"
rm -f "$TARBALL"

echo "[4/7] Writing .env on box (secrets stay on box; not printed here)..."
# Build .env content entirely in-process; pipe via stdin — never touches a local file
ssh "${SSH_OPTS[@]}" "$AWS_HOST" "cat > '$REMOTE_DIR/.env'" <<ENVEOF
# Generated by deploy_aws.sh on $(date -u)
# Do not commit this file.

# ── Database ──────────────────────────────────────────────────────────────────
DATABASE_URL=postgresql+psycopg://pricewatch:${POSTGRES_PASSWORD}@postgres:5432/pricewatch
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ── JWT ───────────────────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30
REFRESH_TOKEN_EXPIRE_DAYS=7

# ── Telegram (optional) ───────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}

# ── App ───────────────────────────────────────────────────────────────────────
APP_ENV=production
LOG_LEVEL=INFO
ENVEOF

ssh "${SSH_OPTS[@]}" "$AWS_HOST" "chmod 600 '$REMOTE_DIR/.env' && echo '  .env written (mode 0600).'"

echo "[5/7] Verifying Docker on box..."
ssh "${SSH_OPTS[@]}" "$AWS_HOST" "
    docker version --format 'Docker {{.Server.Version}}' || {
        echo 'ERROR: Docker not found on box. Install Docker CE first.' >&2
        echo 'See docs/DEPLOY.md § Remote box prerequisites.' >&2
        exit 1
    }
    docker compose version 2>/dev/null || {
        echo 'ERROR: docker compose (V2 plugin) not found.' >&2
        exit 1
    }
    echo '  Docker OK.'
"

echo "[6/7] Starting services (docker compose up -d --build)..."
ssh "${SSH_OPTS[@]}" "$AWS_HOST" "
    set -e
    cd '$REMOTE_DIR'

    # Pull base images first to give a clearer progress view
    docker compose pull postgres 2>/dev/null || true

    # Build app image and start everything detached
    docker compose up -d --build

    echo '  Containers started; waiting for postgres healthcheck...'

    # Wait up to 60 s for postgres to become healthy
    TRIES=0
    until docker compose exec postgres pg_isready -U pricewatch -d pricewatch -q 2>/dev/null; do
        TRIES=\$((TRIES + 1))
        if [ \$TRIES -ge 12 ]; then
            echo 'ERROR: postgres did not become healthy within 60 s.' >&2
            docker compose logs postgres | tail -20
            exit 1
        fi
        echo '    waiting for postgres... ('\$TRIES'/12)'
        sleep 5
    done
    echo '  postgres is healthy.'

    echo '  Running alembic migrations...'
    docker compose exec app alembic upgrade head
    echo '  Migrations done.'
"

echo "[7/7] Healthcheck..."
# Give uvicorn a moment to finish starting up
sleep 5
HTTP_CODE=$(ssh "${SSH_OPTS[@]}" "$AWS_HOST" \
    "curl -s -o /dev/null -w '%{http_code}' http://localhost:${APP_PORT}/health || echo 000")

if [ "$HTTP_CODE" = "200" ]; then
    echo "  /health returned 200 — app is up."
else
    echo "  WARNING: /health returned '$HTTP_CODE'. Printing app logs for diagnosis:"
    ssh "${SSH_OPTS[@]}" "$AWS_HOST" "cd '$REMOTE_DIR' && docker compose logs app --tail=40"
    echo ""
    echo "  The app may still be starting. Try again in 10-20 s:"
    echo "    ssh -i $SSH_KEY $AWS_HOST curl http://localhost:${APP_PORT}/health"
fi

echo ""
echo "=== Done. ==="
echo "  Live app  : http://57.182.243.118:${APP_PORT}"
echo "  Swagger UI: http://57.182.243.118:${APP_PORT}/docs"
echo ""
echo "  Useful commands on box (ssh -i $SSH_KEY $AWS_HOST):"
echo "    docker compose -f $REMOTE_DIR/docker-compose.yml logs -f app"
echo "    docker compose -f $REMOTE_DIR/docker-compose.yml restart app"
echo "    docker compose -f $REMOTE_DIR/docker-compose.yml down"
echo ""
echo "  To update code later: just re-run this script."
